### ISSUE TITLE
Add Sponsor Section

### ISSUE THREAD

**Issue by insipx** [ScrantonHacks/website#13]
A page just for sponsors, including:

An email address for sponsorship inquiries

Some information about your event and your team

Sponsor component to display three different sizes of Logos for our sponsors. Look at DubHacks, HackPSU, or HackBU's page for examples

**Comment by Romulus10** [comment]
I started working on this in a new branch. I have to modify some of it then figure out why it's breaking so badly, but it's under way.

**Comment by Romulus10** [comment]
never mind we fixed that.

**Comment by insipx** [comment]
Finished
